### ISSUE TITLE
[BUG] Octave Doubling Down Produces Error

### ISSUE THREAD

**Issue by rpatters1** [Nick-Mazuk/jw-lua-scripts#22]
Whenever I run Octave Doubling Down I get the following error. (What a great script btw.)
<img width="532" alt="Screen Shot 2020-06-17 at 9 48 56 PM" src="https://user-images.githubusercontent.com/11542367/84972475-8e9e6a00-b0e4-11ea-91a5-3d228b48a4ff.png">

**Comment by Nick-Mazuk** [comment]
Should be resolved with the most recent push.
