### ISSUE TITLE
Add ignored folder for parameter text files

### ISSUE THREAD

**Issue by rpatters1** [Nick-Mazuk/jw-lua-scripts#43]
I am currently working on enhancing the hairpin cleanup script by @CJGarciaMusic. It has a number of parameters that would be nice to personalize, such as the padding gap between hairpins and dynamics and whether to extend hairpins **thru** or **to** the final entry.

To this end, I though I might add a library that reads a text file from a subfolder and stores it in the parameters. I have ideas about how to generalize this for any script to use. I just want to be sure y'all think this is a good idea. We could call the folder, say, `script_settings` and put that folder in .gitignore. That way personalized settings would not be tracked in the repo. (One could of course create one's own repo for the script settings, and I probably would.)

Ultimately, any script would have default settings so that if no settings file were found, the script would still run with the default settings.

Anyway, that's my idea.

**Comment by Nick-Mazuk** [comment]
I think the settings could be useful. Just created a PR to add the `script_settings` folder to the .gitignore just in case.

I can forsee a few issues we may run into if we start allowing settings:

1. Multiple scripts may have similar settings
2. The settings folder could get unorganized
3. If every developer has their own format for creating settings, it will be harder to do code review
4. For an individual script, we'd need to keep track of when new settings options are added (e.g., originally the script has 2 settings, but the new version has 3. Then, the script needs to use the previous 2 settings and create a third)

Therefore, I'd propose that we either create some sort of standard for how settings will operate, or just create a function in the library to take care of the settings. That way the function can take care of the edge cases and the developer only needs to worry about using the settings.

**Comment by rpatters1** [comment]
Yes, I have in mind to create a library for getting/putting settings. It's on my list.

**Comment by CJGarciaMusic** [comment]
User Settings are indeed on the list of things to tackle in V2 of JetStream. I was planning on placing them in the Plug-ins folder like the JW plug-in settings. Thanks for getting a head start on this Robert!
