### ISSUE TITLE
Generate docs automatically

### ISSUE THREAD

**Issue by Nick-Mazuk** [Nick-Mazuk/jw-lua-scripts#55]
**Is your feature request related to a problem? Please describe.**

As the repo is growing, especially as the library is growing, I figured it might be time to get some documentation going. This could aid both documenting what certain functions do as well as helping get started with contributing/using the scripts. This issue is mainly concerned over documenting the library code, though.

**Describe the solution you'd like**

In other languages, there are tools to generate documentation automatically from the code (e.g., JSDoc for JavaScript), so I started looking if there was anything for Lua. Turns out, there is.

I propose we add the [Lua docs generator Github Action](https://github.com/marketplace/actions/lua-docs-generator) to the repo. This action will run on every commit/push to the Master branch and generate documentation based on our comments.

```lua
-- library/general_library.lua

--[[ General:library.add_augmentation_dot(entry)
Accepts a FC:NoteEntry() object and adds an augmentation dot. Useful for…
--]]

function library.add_augmentation_dot(entry)
    entry.Duration = bit32.bor(entry.Duration, bit32.rshift(entry.Duration, 1))
end
```

This will generate several MarkDown files, which we can either put in the repo's Wiki (see the "Wiki" tab at the top of the repo), or I can setup a quick site and make it easy to search through all the docs. Either way is fine with me, and if I setup a site, I already have most of the boilerplate done from other projects.

@rpatters1 , @CJGarciaMusic , have any thoughts? If this sounds like something worth doing, I'll go ahead and start exploring the action more to provide more details.

**Comment by rpatters1** [comment]
I've been thinking about this as well, also especially as regards the libraries. Whatever you can figure out sounds great to me.

**Comment by rpatters1** [comment]
I don't mind making a stab at this, but before I do, I'm wondering if there is some standard way to document inputs and outputs. Also, it would be nice if it were not necessary to duplicate the function definition in the comment. Is there a tool that can figure this out automatically?

**Comment by rpatters1** [comment]
After searching a little bit, this git action seems like an easy and practical option. I would suggest standardizing inputs and outputs based on [ExpLua](http://lua-users.org/wiki/ExpLua) (just because it's a very simple notation). At some point we could consider forking the Lua docs generator action to add intelligent interpretation of them.

```lua
-- library/transposition.lua

--[[ Transposition:transposition.chromatic_transpose(note, interval, alteration, simplify)
Transposes a note chromatically by the input chromatic interval. Supports custom key signatures
and mictrotone systems by means of a custom_key_sig.config.txt file. In Finale, chromatic intervals
are defined by a diatonic interval (0 = unison, 1 = second, 2 = third, etc.) and a chromatic adjustment.
So for example, {2, -1} is a minor third, {3, 0} is a perfect fourth, {5, 1} is an augmented sixth, etc.
@ note the FCNote() instance to transpose
@ interval the diatonic interval (negative for transposing down)
@ alteration the chromatic adjustment that defines the chromatic interval (reverse sign for transposing down)
@ [simplify] optional boolean that if true causes the spelling of the transposed note to be simplified
: boolean success if true
--]]
function transposition.chromatic_transpose(note, interval, alteration, simplify)
    [code ...]
end
```

**Comment by Nick-Mazuk** [comment]
I like the idea of standardizing the docs with ExpLua.

I do plan on setting up the docs today. If time, I'll also work on forking the Github action to interpret ExpLua. I looked at the repo, and it doesn't seem too difficult to do this.
