### ISSUE TITLE
Rewrite transposition library to use math instead of MIDI

### ISSUE THREAD

**Issue by rpatters1** [Nick-Mazuk/jw-lua-scripts#56]
I have been thinking about rewriting the transposition library to use math instead of midi, since I figured out how to do it correctly last summer for my plugins. But I am running the idea by here because that code was written originally by @Nick-Mazuk.

Unfortunately, the PDK Framework does not provide access to the custom key signature data. But a workaround would be to add config.txt file support so that a user could easily change the number of steps/octave and the step map to whatever they need them to be. That way we could provide a modicum of support for microtonal scales. I could probably get Ere Lievonen involved from the Finale Powerusers list to help test with microtonal scales.

It will also involve adding table support to the config file parser.

**Comment by Nick-Mazuk** [comment]
You've been busy this last week! I'm totally on board with rewriting the transposition library to use math instead of MIDI. It should make it much easier to use and debug. Saw that you already added some PRs for this. Checking them out now!

**Comment by rpatters1** [comment]
Closing this one as well.
