### ISSUE TITLE
Pitch transform harmonics 5th produces incorrect result [BUG]

### ISSUE THREAD

**Issue by rpatters1** [Nick-Mazuk/jw-lua-scripts#58]
**Describe the bug**
This function transposes the sounding pitch down 2 octaves and then the touch note a fifth below that. The correct way to achieve the sounding pitch is to transpose it down **1** octave and then the touch note a fifth below that.

**To Reproduce**
1. Open a file with notes
2. Run Pitch Transpose Harmonics 5th script
3. See that the resulting harmonic sounds an octave lower than the original pitch selected.

**Expected behavior**
The result should be an octave higher.

**Additional context**
I found this while working on new transposition function. My plan is to submit a fix as part of that project, unless there is a concern about it.

**Comment by Nick-Mazuk** [comment]
I believe you fixed this with https://github.com/Nick-Mazuk/jw-lua-scripts/pull/59, so I'm closing the issue.

Feel free to reopen if that's not the case.

P.S. On GitHub, if a PR fixes an issue, you can make the issue automatically close when the PR is merged. For this, in the PR, just add `close [issue-url]`. For instance in this case:

```
close https://github.com/Nick-Mazuk/jw-lua-scripts/issues/58
```
