### ISSUE TITLE
Configuration vs. parameters

### ISSUE THREAD

**Issue by Nick-Mazuk** [Nick-Mazuk/jw-lua-scripts#90]
@rpatters1, We probably had this discussion a while back, but is there a reason why we used created our own custom configuration library rather than using JW Lua's built-in parameters functionality?

http://jwmusic.nu/jwplugins/wiki/doku.php?id=jwlua:scriptparameters

**Comment by rpatters1** [comment]
I messed around with those parameters and couldn't find much use for them.
What they *should* do is allow you to have multiple menu options that call
the same script with different parameters. But what they actually do is
much less useful than that. (I forget the details now.)

Ultimately, short of that, I think we're better off having a config scheme
that doesn't rely on the JW Lua ui. But I'm open to being persuaded if
y'all can figure out a good use for them.
